Repository statechannels/graph-payments, pull requests merged in 2021-02, with the labels that each got.

#20 ci: add github workflows for publishing to npm
  .github/workflows/publish-canary.yml
  .github/workflows/publish.yml
Labels: :carrot: conventional, 🧹 chore

#25 docs: update readme
  packages/statechannels-contracts/readme.md
Labels: :carrot: conventional, 📖 documentation

#22 Use ensureChannelsOpen to deal with race conditions
  packages/payments/src/__tests__/payment-manager.test.ts
  packages/payments/src/channel-manager.ts
Labels: :carrot: conventional, 🐛 bug

#26 fix: update statechannels packages to latest release
  packages/e2e-testing/package.json
  packages/payments/package.json
  packages/receipts/package.json
  packages/statechannels-contracts/package.json
  yarn.lock
Labels: :carrot: conventional

#28 Refactor e2e-test utilities into separate file
  packages/e2e-testing/__tests__/e2e-utils.ts
  packages/e2e-testing/__tests__/e2e.test.ts
  packages/e2e-testing/package.json
  packages/e2e-testing/tsconfig.json
  yarn.lock
Labels: :carrot: conventional

#21 chore: create spike template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/spike.md
Labels: 🧹 chore

#39 fix: publish action refers to main
  .github/workflows/publish.yml
Labels: :carrot: conventional

#38 chore: add upgrade-statechannels-latest GH action
  .github/workflows/upgrade-statechannels-latest.yml
Labels: 🧹 chore

#32 Add network errors to ledger funding integration test
  packages/e2e-testing/__tests__/bad-network.test.ts
  packages/e2e-testing/__tests__/e2e-utils.ts
  packages/e2e-testing/package.json
  packages/e2e-testing/src/payment-server.ts
  packages/payments/src/channel-manager.ts
Labels: :carrot: conventional

#37 chore: configure wallet loggers in payment/receipt servers
  packages/e2e-testing/src/payment-server.ts
  packages/e2e-testing/src/receipt-server.ts
Labels: :carrot: conventional

#49 chore: Update PR template to match statechannels repo
  .github/pull_request_template.md
Labels: 🧹 chore

#42 Log system stats in e2e tests
  .circleci/config.yml
  bin/log_memory.sh
Labels: 🧹 chore

#57 Re-enable Flickering Test
  .circleci/config.yml
  packages/e2e-testing/src/payment-server.ts
  packages/e2e-testing/src/receipt-server.ts
Labels: :carrot: conventional, ✨ enhancement
