Repository statechannels/graph-payments, pull requests merged in 2021-01, with the labels that each got.

#10 Update to Latest version of StateChannels
  packages/e2e-testing/__tests__/e2e.test.ts
  packages/e2e-testing/package.json
  packages/e2e-testing/src/payment-server.ts
  packages/e2e-testing/src/receipt-server.ts
  packages/payments/package.json
  packages/payments/src/__tests__/payment-manager.test.ts
  packages/payments/src/__tests__/test-channel-manager.ts
  packages/payments/src/__tests__/test-payment-manager.ts
  packages/payments/src/channel-cache/__tests__/cache.test.ts
  packages/payments/src/channel-manager.ts
  packages/payments/src/payment-manager.ts
  packages/receipts/package.json
  packages/receipts/src/__tests__/receipt-manager.test.ts
  packages/receipts/src/receipt-manager.ts
  packages/statechannels-contracts/package.json
  yarn.lock
Labels: :carrot: conventional, 🧹 chore

#4 skip prepare during github action
  .github/workflows/upgrade-statechannels-next.yml
Labels: :carrot: conventional

#11 ci: remove duplicated step
  .circleci/config.yml
Labels: :carrot: conventional

#2 ci: fix typo in file name of e2e-test logs
  .circleci/config.yml
Labels: :carrot: conventional

#14 ci: upgrade-statechannels-next checks we're on main
  .github/workflows/upgrade-statechannels-next.yml
Labels: :carrot: conventional, 🧹 chore

#13 refactor: e2e test script orders code according to convention
  packages/e2e-testing/__tests__/e2e.test.ts
Labels: :carrot: conventional, 🧹 chore

#12 fix: exit db-utils yargs script after async handler resolves
  packages/payments/scripts/db-utils.ts
Labels: 🐛 bug

#16 chore: mirror linting configuration from statechannels repo, and apply resulting changes
  .eslintrc.js
  packages/e2e-testing/__tests__/e2e.test.ts
  packages/e2e-testing/__tests__/stress.test.ts
  packages/e2e-testing/chain-setup.ts
  packages/e2e-testing/package.json
  packages/e2e-testing/scripts/flamegraphs.ts
  packages/e2e-testing/src/constants.ts
  packages/e2e-testing/src/external-server.ts
  packages/e2e-testing/src/funding-test-runner.ts
  packages/e2e-testing/src/load-generator.ts
  packages/e2e-testing/src/payment-server.ts
  packages/e2e-testing/src/receipt-server.ts
  packages/e2e-testing/src/utils.ts
  packages/payments/package.json
  packages/payments/scripts/db-utils.ts
  packages/payments/src/__tests__/cache-test-utils.ts
  packages/payments/src/__tests__/crash-test-dummies.ts
  packages/payments/src/__tests__/extract-capacities.test.ts
  packages/payments/src/__tests__/fake-indexer.ts
  packages/payments/src/__tests__/payment-manager.test.ts
  packages/payments/src/__tests__/setup.ts
  packages/payments/src/__tests__/test-channel-manager.ts
  packages/payments/src/__tests__/test-payment-manager.ts
  packages/payments/src/channel-cache/__tests__/cache.test.ts
  packages/payments/src/channel-cache/postgres-cache.ts
  packages/payments/src/channel-manager.ts
  packages/payments/src/db/knex.ts
  packages/payments/src/db/utils.ts
  packages/payments/src/insights.ts
  packages/payments/src/payment-manager.ts
  packages/payments/src/utils.ts
  packages/receipts/package.json
  packages/receipts/src/__tests__/receipt-manager.test.ts
  packages/receipts/src/receipt-manager.ts
  packages/statechannels-contracts/package.json
  packages/statechannels-contracts/src/utils/__tests__/app-data.test.ts
  packages/statechannels-contracts/src/utils/__tests__/benchmark.ts
  packages/statechannels-contracts/src/utils/state-transitions.ts
  packages/statechannels-contracts/test/attestationApp.test.ts
  yarn.lock
Labels: :carrot: conventional

#5 chore: updated pull request template to exclude GH issue
  .github/pull_request_template.md
Labels: :carrot: conventional, 🧹 chore

#15 Only warm up threads if the wallet is multi-threaded
  packages/payments/src/payment-manager.ts
  packages/receipts/src/receipt-manager.ts
Labels: :carrot: conventional
